theme = "rose_pine"

[editor]
line-number = "absolute"
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "read-only-indicator", "diagnostics"]
center = ["spinner","file-name","file-modification-indicator"]
right = ["file-type","position"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
