"$schema" = 'https://starship.rs/config-schema.json'

palette = "rose-pine"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "pine"

[character]
success_symbol = "[❯](iris)"
error_symbol = "[❯](love)"
vimcmd_symbol = "[❮](foam)"

[git_branch]
format = "[$branch]($style)"
style = "rose"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "foam"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "overlay"

[cmd_duration]
format = "[$duration]($style) "
style = "gold"

[python]
format = "[$virtualenv]($style) "
style = "overlay"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
